# Change these first
owner: saxobroko # Your GitHub username
repo: SaxoStatus # Your GitHub repository name

# Add your sites here
sites:
  - name: Home
    url: https://saxobroko.com
  - name: Blog
    url: https://blog.saxobroko.com
  - name: PhotoShare
    url: https://share.saxobroko.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.saxobroko.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://saxobroko.com/favicon.png
  favicon: https://saxobroko.com/favicon.png
  name: Status- Saxo_Broko
  theme: dark
  introTitle: "Saxo_Broko's Uptime Status"
  introMessage: Use this to see if theres a problem with the website, or you
  navbar:
    - title: Home
      href: https://saxobroko.com
    - title: Blog
      href: https://blog.saxobroko.com
    - title: PhotoShare
      href: https://share.saxobroko.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
